---
name: "CI-CD"

on:
  push:
    branches:    
      - master
      - main

jobs:
  CI-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Remove git directories
      run: |
        rm -rf .git*
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: .
        
  CI-Test:
    runs-on: ubuntu-latest
    needs: CI-Build
    steps:
      - name: "Check file existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "README.md"
          fail: true
  
  CD:
    runs-on: "ubuntu-latest"
    needs: CI-Test

    steps:
    - uses: actions/download-artifact@v3
      with:
        path: .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy files to the test bucket with the AWS CLI
      run: |
        aws s3 sync my-artifact s3://mybucket-yt-test/
