---
name: "deploy-release"

on:
  workflow_run:
    workflows: ["release"]
    branches: [master]
    types: 
      - completed
jobs:
  deploy-release:
    name: "Deploy Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/download-artifact@v3

