---
name: "release"

on:
  push:
    branches:    
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/upload-artifact@v3
